# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
 . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

ca () {
  spack load miniconda3
  conda activate $1
  spack unload miniconda3
}
echo "loading spack modules"
spack load nano 




# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/appl/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/miniconda3-4.10.3-bgxkfvih5n7x4hyikk6stosxeo5hajxx/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/appl/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/miniconda3-4.10.3-bgxkfvih5n7x4hyikk6stosxeo5hajxx/etc/profile.d/conda.sh" ]; then
        . "/appl/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/miniconda3-4.10.3-bgxkfvih5n7x4hyikk6stosxeo5hajxx/etc/profile.d/conda.sh"
    else
        export PATH="/appl/spack/opt/spack/linux-rocky8-zen/gcc-8.5.0/miniconda3-4.10.3-bgxkfvih5n7x4hyikk6stosxeo5hajxx/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<